var docViewer={currentPage:1,prevPage:1,nextPage:2,loadedPages:1,docTotalPages:null,totalPages:null,permId:null,animateSpeed:600,pageSlices:4,zoomStep:100,imagePath:null,imageUrlParams:null,viewer:null,docOverlay:null,docCoverT:null,docCoverB:null,adjustCoverSecurity:false,isTextBased:false,accessTimeout:false,loadInterval:null,loggedIn:false,simpleView:false,fullscreen:false,didScroll:false,didResize:false,lastScrollTop:0,delta:50,toolbarY:0,recImpressionId:null,refImpressionId:null,psPdfKitViewer:false,init:function(){docViewer.docTotalPages=parseInt($('#docControlPage strong').text());docViewer.totalPages=$('#doc_meta_data').metadata().total_pages;docViewer.permId=$('#doc_meta_data').metadata().perm_id;docViewer.imagePath=$('#doc_meta_data').metadata().doc_image_repo;docViewer.imageUrlParams=$('#doc_meta_data').metadata().image_url_params;docViewer.viewer=$('#docViewer');docViewer.docOverlay=$('#docOverlay');docViewer.docCoverT=$('#docCoverTop img');docViewer.docCoverB=$('#docCoverBottom img');docViewer.recImpressionId=$('#impression_id').metadata().rec_impression_id;docViewer.refImpressionId=$('#impression_id').metadata().ref_impression_id;if($('.pageToolbar').length>0){docViewer.toolbarY=$('.pageToolbar').offset().top;}
if($('#ps_pdf_meta_data').length>0){docViewer.psPdfKitViewer=true;}
$(window).scroll(function(event){docViewer.didScroll=true;});$(window).resize(function(event){docViewer.didResize=true;});setInterval(function(){if(docViewer.didScroll){docViewer.scrollEvent();docViewer.adjustCovers();docViewer.didScroll=false;}},250);setInterval(function(){if(docViewer.didResize){docViewer.scrollEvent();docViewer.adjustToWindow();docViewer.didResize=false;}},250);$(window).load(docViewer.adjustOverlay);$(window).keydown(docViewer.hotKeys);docViewer.adjustSideContent();if(!docViewer.psPdfKitViewer){docViewer.insertPagePlaceholders();}
docViewer.adjustToWindow();$('#docLoadingOverlay').width($('#docViewer').width()-2);$('#docLoadingOverlay').height($('#docViewer').height()-2);$('#docLoadingOverlay').remove();window.setTimeout(function(){docViewer.accessTimeout=true;$('#scrollLoading').html('Please <a href="#refresh">refresh your browser</a> to load the remaining pages');$('#scrollLoading a').click(function(e){e.preventDefault();location.reload();});},1000*60*55);docViewer.autoLoadPage();$(window).load(docViewer.adjustCovers);docViewer.adjustCoverSecurity=true;if($('#purchasePreLogin').length<=0){docViewer.loggedIn=true;}
if($('#simpleViewCurrentPage').length>0){docViewer.simpleView=$('#doc_meta_data').metadata().currentPage;}
$('#scrollLoading').hide();docViewer.setCurrentPage(1);$('.modal.autoload').modal('show');if($('#bsModalRental').length>0){$('.rentArticle').click(function(e){e.preventDefault();docViewer.openDocRentalModul('preview-reminder');});$('#bsModalRental #docSignUpPlanFree, #basicPlan').click(function(e){e.preventDefault();rentalActions.toPane('#purchaseSignUpPlans','#purchaseSignUpFlow');trackEvent('doc-viewer','modul/signup/select/basic',docViewer.permId,false);});$('#backToSelection').click(function(e){e.preventDefault();rentalActions.toPane('#purchaseSignUpFlow','#purchaseSignUpPlans');trackEvent('doc-viewer','modul/signup/back',docViewer.permId,false);});$('#bsModalRental .cancel').click(function(e){e.preventDefault();docViewer.closeDocRentalModul('cancel');});}else{$('.rentArticle').click(function(e){e.preventDefault();docViewer.openDocRentalPane('preview-reminder');});}
if($('.paymentFormSelection').length>0){$('.paymentFormSelection').closest('.modal').css({width:'auto','margin-left':function(){return-($(this).width()/2);}});$('.paymentFormSelection').closest('.modal-body').css({overflow:'visible'});}
if($('#textPage').length>0){docViewer.isTextBased=true;$('#textPage').disableSelection();$('.docZoom').hide();}
$('.turnOnHtml5').click(function(e){e.preventDefault();$.cookie('useHtml5Viewer',true,{expires:7,path:'/'});location.reload();});$('.js-turnOnEnhancedViewer').click(function(e){e.preventDefault();$.cookie('useHtml5Viewer',true,{expires:7,path:'/'});var docUrl=$(this).attr('href');location.href=docUrl;});$('.contentMain').disableSelection();if(docViewer.docTotalPages>=100){$('#docCurrentPage').attr('maxlength','3');}else if(docViewer.docTotalPages>=10){$('#docCurrentPage').attr('maxlength','2');}else{$('#docCurrentPage').attr('maxlength','1');}
$('#docCurrentPage').keyup(function(e){var code=(e.keyCode?e.keyCode:e.which);if(code==13){var pageValue=$(this).val();if(isNaN(parseInt(pageValue))){return false;}
if(docViewer.simpleView){window.location.href=$('#baseDocUrl').text()+'/'+pageValue;}else{docViewer.goToPage(pageValue);}
$(this).blur();}}).focus(function(e){$('#docControlPage').addClass('focus');}).blur(function(e){$('#docControlPage').removeClass('focus');}).css('padding-right',$('#docControlPage span').width()+10);$('#docControlPage span').click(function(e){$('#docCurrentPage').focus();});if($('#autoClick').length>0){var autoClick=$('#autoClick').text();if(autoClick=='rental'){if($('#rentalButton .statusButton').length<=0){if($('#bsModalRental').length>0){docViewer.openDocRentalModul('auto');}else{docViewer.openDocRentalPane('auto');}}}else if(autoClick=='freemium-rental'){$('#bsModalRentalFreemium').modal('show');}else if(autoClick=='freemium-rental-5pack'){if($('#bsModalRentalFreemium').length>0){$('#bsModalRentalFreemium').modal('show');}}else if(autoClick=='download'){$('#bsDownloadModal').modal('show');}}
MLT.getRelatedArticles($('#mltList'));if($('#purchaseLoginFlow').length>0){$('#purchaseLoginFlow').modal('show');}
if($('.cvv2').length>0){$('.cvv2').tooltip();}
if($('#doc_meta_data').length>0&&($('#doc_meta_data').metadata().currentlyRenting=='true'||$('#doc_meta_data').metadata().internal_rental_state=='free')&&docViewer.psPdfKitViewer){rentalActions.loadPSPDFKit('#pspdfkit',$('#ps_pdf_meta_data').metadata().docId,$('#ps_pdf_meta_data').metadata().jwt);}
docViewer.setupDocDetailsBlock();docViewer.setupPaginator();$(window).scroll();},adjustToWindow:function(){docViewer.adjustCovers();docViewer.adjustOverlay();docViewer.adjustSideContent();if($('#newUserHeroIntroDocBG').length>0){$('#newUserHeroIntroDocBG').height($('#docViewer').height());}},insertPagePlaceholders:function(){var loadingMsg;var baseDocUrl=$('#baseDocUrl').text();for(var i=2;i<=docViewer.totalPages;i++){loadingMsg='<div class="loading">'+'<h2><i class="icon-spin icon-spinner icon-large"></i> Loading...</h2></div>';$('#pageWrapper').append('<div class="page loading" id="page'+i+'">'+loadingMsg+'</div><p class="pageNumber">Page '+i+'</p>');$('#page'+i).height($('#page1').height());}},scrollEvent:function(){docViewer.adjustToolbar();if($('#scrollLoading').is(':visible, :animated')){return false;}
$('#pageWrapper .page').each(function(){if($(document).scrollTop()<($(this).offset().top+$(this).height()-$(window).height()/2)){var currentPage=$(this).attr('id').split('page')[1];docViewer.setCurrentPage(currentPage);docViewer.getPage(currentPage);return false;}});$('.page.loading').height($('#page1').height());if(docViewer.isNearBottom()){docViewer.getPage(docViewer.nextPage);}},adjustToolbar:function(){var st=$(window).scrollTop();if(Math.abs(docViewer.lastScrollTop - st)<=docViewer.delta){return;}
if(st<docViewer.toolbarY){$('.dd-docview-toolbar').removeClass('dd-docview-toolbar-down').removeClass('dd-docview-toolbar-up');$('#docViewControlTray').removeClass('docViewControlTray-fixed-toolbarDown');}else if(st>docViewer.lastScrollTop&&st>docViewer.toolbarY){$('#docViewControlTray').removeClass('docViewControlTray-fixed-toolbarDown');}else{if(st+$(window).height()<$(document).height()){$('#docViewControlTray').addClass('docViewControlTray-fixed-toolbarDown');}}
docViewer.lastScrollTop=st;},hotKeys:function(e){if($('input:focus, textarea:focus').length<=0){var code=(e.keyCode?e.keyCode:e.which);if(code==74||code==219){docViewer.scrollUp('hotkey/'+code);}else if(code==75||code==221){docViewer.scrollDown('hotkey/'+code);}else{if(code==189||code==109){docViewer.zoomOut('hotkey/'+code);}else if(code==187||code==107){docViewer.zoomIn('hotkey/'+code);}}}},zoomIn:function(source){var pageWidth=$('#docViewer .page .img').width();if(pageWidth<2000){$('#docViewer .page .img').width(pageWidth+docViewer.zoomStep);docViewer.adjustDocViewer();if(pageWidth>1900)$('.docZoomIn').addClass('disabled');$('.docZoomOut').removeClass('disabled');}else{$('.docZoomIn').addClass('disabled');}
docViewer.adjustOverlay();if(source!==undefined){trackEvent('doc-viewer','zoom-in/'+source,docViewer.permId,false);}else{trackEvent('doc-viewer','zoom-in',docViewer.permId,false);}},zoomOut:function(source){var pageWidth=$('#docViewer .page .img').width();if(pageWidth>950){$('#docViewer .page .img').width(pageWidth-docViewer.zoomStep);docViewer.adjustDocViewer();if(pageWidth<1050)$('.docZoomOut').addClass('disabled');$('.docZoomIn').removeClass('disabled');}else{$('.docZoomOut').addClass('disabled');}
docViewer.adjustOverlay();if(source!==undefined){trackEvent('doc-viewer','zoom-out/'+source,docViewer.permId,false);}else{trackEvent('doc-viewer','zoom-out',docViewer.permId,false);}},zoomReset:function(source){return;},isFullScreen:function(){return docViewer.fullscreen;},adjustSideContent:function(){if($('article').height()<$('.controlTray-ContentBody').height()){$('.controlTray-ContentBody').height($('article').height());}},adjustOverlay:function(){docViewer.docOverlay.width($('#pageWrapper').width());docViewer.docOverlay.height($('#pageWrapper').height());},adjustCovers:function(){var topAdjustment=$(document).scrollTop()-docViewer.viewer.offset().top;var bottomAdjustment=docViewer.viewer.offset().top+docViewer.viewer.height()-$(document).scrollTop()-$(window).height();var docViewerWidth=docViewer.viewer.width();if(topAdjustment>0){docViewer.docCoverT.height(topAdjustment).show();docViewer.docCoverT.width(docViewerWidth);}else{docViewer.docCoverT.hide();}
if(bottomAdjustment>0){docViewer.docCoverB.height(bottomAdjustment).show();docViewer.docCoverB.width(docViewerWidth);}else{docViewer.docCoverB.hide();}},adjustDocViewer:function(){var marginAdjustment;var pageMargin=$(window).width()-$('#docViewer .page .img').width();if(pageMargin>40){marginAdjustment=pageMargin/2;}else{marginAdjustment=20;}
$('#docViewer').css({width:$('#docViewer .page .img').width()+5,marginLeft:marginAdjustment});docViewer.adjustCovers();},setCurrentPage:function(current){current=parseInt(current);if(current<=1){docViewer.currentPage=1;docViewer.prevPage=1;docViewer.nextPage=docViewer.currentPage+1;}else if(current>=docViewer.totalPages){docViewer.currentPage=docViewer.totalPages;docViewer.prevPage=docViewer.currentPage-1;docViewer.nextPage=docViewer.totalPages;}else{docViewer.currentPage=current;docViewer.prevPage=current-1;docViewer.nextPage=current+1;}
if($(document).scrollTop()<$('#docViewer').offset().top){$('#docControlPrev').addClass('disabled');}else{$('#docControlPrev').removeClass('disabled');}
if(($(document).scrollTop()+$(window).height())>($('#docViewer').offset().top+$('#docViewer').height())){$('#docControlNext').addClass('disabled');}else{$('#docControlNext').removeClass('disabled');}
if(docViewer.simpleView){$('#docCurrentPage').val(docViewer.simpleView);}else{$('#docCurrentPage').val(current);$('.toSimpleView').attr('href',$('#baseDocUrl').text()+'/'+current);}},autoLoadPage:function(){docViewer.loadInterval=window.setTimeout(function(){if($('.page.loading').length>0){var nextUnloadedPage=$('.page.loading').attr('id').split('page')[1];docViewer.getPage(nextUnloadedPage);}},2000);},isNearBottom:function(){if(navigator.userAgent.match(/iPad/i)!==null){if(($(document).scrollTop()+$(window).height())>($('#docViewerWrapper').offset().top-$(document).scrollTop()-($(window).height()*2))){return true;}}else{if(($(document).scrollTop()+$(window).height()*2)>($('#docViewerWrapper').offset().top+$('#docViewerWrapper').height())){return true;}}
return false;},getPage:function(page,o){var options={transition:false,scroll:false,pages:1,callback:function(){docViewer.adjustToWindow();}};if(o!==undefined){if(o.transition!==undefined)options.transition=o.transition;if(o.scroll!==undefined)options.scroll=o.scroll;if(o.pages!==undefined)options.pages=o.pages;if(o.callback!==undefined)options.callback=o.callback;}
if(page>docViewer.totalPages||$('#page'+page+'.loading').length<1){return false;}
if(docViewer.accessTimeout){trackEvent('doc-viewer','accessTimeout',docViewer.permId,false);}else{var sliceArray=[];window.clearTimeout(docViewer.loadInterval);docViewer.getSlice(page,1,sliceArray,options);trackPageview("/doc-viewer/page/"+page+"/"+docViewer.permId);}},getSlice:function(page,slice,sliceArray,options){var offset=(docViewer.getUrlParameter('offset'));if(offset){offset=parseInt(offset);}else{offset=0;}
$('<img id="page'+page+'s'+slice+'" class="img" style="display:none;" />').attr('src',docViewer.imagePath+docViewer.permId+'/'+(parseInt(page)+offset)+'/'+(slice)+docViewer.imageUrlParams).attr('meta',docViewer.imagePath+docViewer.permId+'/'+(parseInt(page)+offset)+'/'+(slice)+docViewer.imageUrlParams).load(function(){sliceArray.push($(this));if(slice<docViewer.pageSlices){docViewer.getSlice(page,slice+1,sliceArray,options);}else{docViewer.insertLoadedPage(page,sliceArray,options);}}).error(function(){window.setTimeout(function(){docViewer.getSlice(page,slice,sliceArray,options);},1000*5);});},insertLoadedPage:function(page,sliceArray,options){var getPageCallBack=function(){docViewer.adjustOverlay();docViewer.loadedPages=page;if(docViewer.loadedPages<docViewer.totalPages){docViewer.autoLoadPage();}
if(docViewer.isNearBottom()){docViewer.getPage(docViewer.nextPage);}};docViewer.nextPage+=1;var newPage=$('<p id="page'+page+'" class="page"></p>');var pagePlaceholder=$('#page'+page);for(var i=0;i<sliceArray.length;i++){newPage.append(sliceArray[i]);}
if(options.transition){pagePlaceholder.replaceWith(newPage).hide().slideDown(function(){getPageCallBack();options.callback();});}else{pagePlaceholder.replaceWith(newPage);getPageCallBack();options.callback();}
if(docViewer.isFullScreen()){newPage.children('.img').width($('#docViewer .page .img').width());}
if(options.scroll){$.scrollTo('#page'+page,$(window).height(),{easing:'easeOutQuart'});docViewer.setCurrentPage(page);}},getNextPage:function(nextPage,stopAt){if(nextPage<stopAt){docViewer.getPage(nextPage,{transition:false,callback:function(){docViewer.getNextPage(nextPage+1,stopAt);}});}else{docViewer.getPage(stopAt,{transition:false,scroll:true,callback:function(){$('#docControlLoading').addClass('hide');}});}},goToPage:function(page){if(page<1){page=1;}
if(page>docViewer.totalPages){page=docViewer.totalPages;}
if($('#page'+page).length>0){$.scrollTo('#page'+page,$(window).height(),{easing:'easeOutQuart'});}else{for(var i=1;i<page;i++){if($('#page'+i).length<=0){$('#docControlLoading').removeClass('hide');docViewer.getNextPage(i,page);break;}}}
trackPageview("/doc-viewer/goto/page/"+page+"/"+docViewer.permId);},openDocRentalModul:function(source){if(docViewer.isFullScreen()){docViewer.exitFullScreen('preview-reminder');}
$('#bsModalRental').modal('show');source=(!source)?"":source;var modalType=(docViewer.loggedIn)?"rental":"signup";trackEvent('doc-viewer',modalType+'-modul/open',source,false);},closeDocRentalModul:function(source){$('#bsModalRental').modal('hide');source=(!source)?"":source;var modalType=(docViewer.loggedIn)?"rental":"signup";trackEvent('doc-viewer',modalType+'-modul/close',source,false);},closeDocDownloadModul:function(source){$('#bsDownloadModal').modal('hide');},setupPaginator:function(){$('.pagination').pagination({pages:$('#doc_meta_data').metadata().plain_total_pages,displayedPages:12,edges:3,currentPage:$('#doc_meta_data').metadata().currentPage,hrefTextPrefix:$('#baseDocUrl').text()+'/',hrefTextSuffix:$('#doc_meta_data').metadata().simpleDocSuffix,selectOnClick:false});$('.pagination li a').click(function(){$(this).html('<i class="icon-spinner icon-spin"></i>');});},setupDocDetailsBlock:function(){$('.docDetailsToggle').click(function(e){e.preventDefault();$('.docDetailsBlock').toggle(200);});},showFreemiumPurchaseOptions:function(){if(docViewer.isFullScreen()){docViewer.exitFullScreen('show-freemium-purchase-options');}
if($('#freemiumPurchaseOptions').is(':visible')){return;}
$('#freemiumPurchaseOptions').show();$('.html5message').hide();$('.pagination').hide();if(navigator.userAgent.indexOf("MSIE")>-1){$('#docViewer').slideUp();$('body').scrollTo('#freemiumPurchaseOptions');}else{var selector=$('.html5PageWrapper').length?'.html5PageWrapper':'#pageWrapper';$.each($(selector).children(),function(index,item){if(index<2){return;}
$(item).remove();});$('body').scrollTo('#freemiumPurchaseOptions',500);}},rotate:function(degrees){return;},getUrlParameter:function(name){name=name.replace(/[\[]/,'\\[').replace(/[\]]/,'\\]');var regex=new RegExp('[\\?&]'+name+'=([^&#]*)');var results=regex.exec(location.search);return results===null?'':decodeURIComponent(results[1].replace(/\+/g,' '));}};$(document).ready(function(){docViewer.init();});